### ISSUE TITLE
Add constraint to check stand_structure and num_of_layers

### ISSUE THREAD

**Issue by edwardsmarc** [CASFRI/CASFRI#592]
STAND_STRUCTURE should be checked against the number of LYR layers.

If STAND_STRUCTURE is SINGLE_STORIED, there should only be one LYR row.
If STAND_STRUCTURE is MULTI_STORIED, there should be more than one LYR row.

Can also check num_of_layers. Should sum to the total number of LYR and NFL rows.

Not sure if we can count rows with the contraints function? Might need it's own query.

**Comment by pedrogit** [comment]
There is already a constraint (1.17) making sure STAND_STRUCTURE fits with NUM_OF_LAYERS. It checks that:

((stand_structure = ''MULTI_LAYERED'' OR 
  stand_structure = ''HORIZONTAL'' OR 
  stand_structure = ''COMPLEX'' OR
  stand_structure = ''SINGLE_LAYERED'') AND 
  num_of_layers > 1) OR 
((stand_structure = ''SINGLE_LAYERED'' OR 
  stand_structure = ''COMPLEX'' OR
  stand_structure = ''HORIZONTAL'') AND 
  num_of_layers = 1) OR 
  num_of_layers = -8886 OR -- UNKNOWN_VALUE
  stand_structure = ANY(TT_IsMissingOrNotInSetCode())

If I understand well this issue is about matching STAND_STRUCTURE with the number of LYR and NFL rows, no only with the global nomber of rows?

Does the current constraint (1.17) need to be revisited?

**Comment by edwardsmarc** [comment]
Correct, constraint 1.17 checks that stand structure makes sense based on num_of_layers.

Notice that in 1.17 SINGLE_LAYERED can have 1, or more than 1 total layers (this is because stand structure is based only on LYR layers, so you could have a single LYR row and an NFL row which would produce SINGLE_LAYERED and NUM_OF_LAYERS = 2).  

The only test on MULTI_LAYERED is that is has to have >1 layer.

We would two more detailed constraints to do the following:

1. Check that STAND_STRUCTURE is correct based on the number of LYR rows.
  - e.g. if SINGLE_LAYERED, 1 LYR row. If MULTI_LAYERED, >1 LYR row.

2. Check that NUM_OF_LAYERS matches total count of LYR and NFL rows.

**Comment by pedrogit** [comment]
Do that means a constraint like 1.17, based only on STAND_STRUCTURE and NUM_OF_LAYERS, CAN NOT be applied. It must be replaced by a more precise constraint linking STAND_STRUCTURE with the number of LYR layers only. Is this correct?

**Comment by edwardsmarc** [comment]
Yes, 1.17 would be redundant once we have the new constraint. We can replace it with tests 1. and 2. described in my comment above. I've edited my above comment to include COMPLEX and HORIZONTAL.

**Comment by pedrogit** [comment]
Release 5.3.1: NT03 still has 32 row with STAND_STRUCTURE = "MULTI_LAYERED" and only 1 LYR layer a nd and 18 rows with STAND_STRUCTURE = "COMPLEX" and 2 LYR layer.

**Comment by edwardsmarc** [comment]
This is related to #739 and should have been fixed by edits to TT_row_translation_rule_nt_lyr().

**Comment by pedrogit** [comment]
In CASFRI 5.3.1 the 32 NT03 MULTI_LAYERED rows have been fixed but not the 18 COMPLEX ones. Leaving open.

**Comment by edwardsmarc** [comment]
There must be rows in the source data that report COMPLEX structure but also have 2 layers of trees reported. Usually COMPLEX stands have a single LYR record. 

There is actually nothing in the specs stating that COMPLEX stands have to be 1 layer. But they usually are in the source data. I've added a comment to the specs stating that COMPLEX stands are usually 1 layer but in some cases multiple LYR layers are reported.
