### ISSUE TITLE
Constraints - ON01 SRC_INV_AREA error code -9999 is not valid

### ISSUE THREAD

**Issue by edwardsmarc** [CASFRI/CASFRI#692]
constraint 1.20

I added isGreaterThan to catch zero's. But it needs to assign an error code of -8888 instead of -9999. 

This will effect all inventories with zero values for source area.

**Comment by edwardsmarc** [comment]
Constraints need to be checked before closing

**Comment by pedrogit** [comment]
As the constraint were not passing for this and there was no issue referenced in the constraints, I changed the list of acceptable error code for SRC_INV_AREA from TT_IsMissingOrInvalidNumber() to TT_IsMissingOrInvalidRange() so that now -9999 is an acceptable value.

I found that this was making sense since we can consider values that can not be negative as a range delimited on one side only. If this make sence then we should review all attribute that can not be negative and use TT_IsMissingOrInvalidRange() instead of TT_IsMissingOrInvalidNumber() for them.

BTW -9999 (OUT_OF_RANGE) should not have been replace by -8888 (NULL_VALUE) which is already tested by notNull(). The equivalent of -9999 (OUT_OF_RANGE) for non bounded numeric values is -9997 (INVALID_VALUE) which is part of the set defined by TT_IsMissingOrInvalidNumber().

**Comment by edwardsmarc** [comment]
I agree that select TT_IsMissingOrInvalidRange() makes sense here. This could apply to many attributes. Note there are also many other cases where we catch zero values and report NULL_VALUE. Seems like we should change those to either INVALID_VALUE or OUT_OF_RANGE based on your comment above?

**Comment by pedrogit** [comment]
> I agree that select TT_IsMissingOrInvalidRange() makes sense here. This could apply to many attributes. Note there are also many other cases where we catch zero values and report NULL_VALUE. Seems like we should change those to either INVALID_VALUE or OUT_OF_RANGE based on your comment above?

When 0 means "nothing" then it should return NULL_VALUE. When it's outside the valid range, it should return OUT_OF_RANGE. When it's just an invalid value then we should return INVALID_VALUE.

**Comment by edwardsmarc** [comment]
OK I'll make a list of cases where we need to change the error code for catching zeros....

**Comment by edwardsmarc** [comment]
For example, 
- a zero for SRC_INV_AREA would be OUT_OF_RANGE?
- a zero for PHOTO_YEAR would be INVALID_VALUE?
- a zero for SPECIES_PER_x would be NULL_VALUE?

**Comment by edwardsmarc** [comment]
Note that DIST_YEAR values of zero are often caught as -8886 (UNKNOWN_VALUE). This is because you can often have DIST_TYPE values that have years of 0. In this case UNKNOWN seems like an appropriate error code. A disturbance year that is not between 1000 - 2000 on the other hand would return -9999 (OUT_OF_RANGE).

**Comment by edwardsmarc** [comment]
All error codes updated. Constraints need to be updated to use TT_IsMissingOrInvalidRange().

**Comment by pedrogit** [comment]
All constraints on the concerned attributes were already set to TT_IsMissingOrInvalidRange() and pass. Closing...
